import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/Banner";
import NavBar from "@/components/nav/navbar";
import Card from "@/components/card/card";
import SectionCards from "@/components/card/section-cards";
import { getVideos, getPopularVideos } from "@/lib/videos";

export async function getServerSideProps() {
  const historicalEpicVideos = await getVideos("historical movie trailer");
  const productivityVideos = await getVideos("productivity");
  const travelVideos = await getVideos("travel");
  const popularVideos = await getPopularVideos();
  console.log({ popularVideos });
  return {
    //, travelVideos, productivityVideos
    props: {
      historicalEpicVideos,
      productivityVideos,
      travelVideos,
      popularVideos,
    },
  };
}

export default function Home({
  historicalEpicVideos,
  productivityVideos,
  travelVideos,
  popularVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Steflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar username="stephen@gmail.com" />
        <Banner
          title="300"
          subTitle="Spartans battle Persians"
          imgUrl="/static/300.jpg"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards
            title="Historical Epic"
            videos={historicalEpicVideos}
            size={"large"}
          />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size={"small"}
          />
          <SectionCards title="Travel" videos={travelVideos} size={"medium"} />
          <SectionCards title="Popular" videos={popularVideos} size={"small"} />
        </div>
      </div>
    </div>
  );
}
