import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/Banner";
import NavBar from "@/components/nav/navbar";
import Card from "@/components/card/card";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="stephen@gmail.com" />
      <Banner
        title="300"
        subTitle="Spartans battle Persians"
        imgUrl="/static/300.jpg"
      />

      <Card imgUrl="/static/300.jpg" size="large" />
      <Card size="medium" />
      <Card imgUrl="/static/300.jpg" size="small" />
    </div>
  );
}
